#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace LawAppModel	
{
	public partial class Holiday
	{
		private int _holidayId;
		public virtual int HolidayId
		{
			get
			{
				return this._holidayId;
			}
			set
			{
				this._holidayId = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private DateTime _holidayDate;
		public virtual DateTime HolidayDate
		{
			get
			{
				return this._holidayDate;
			}
			set
			{
				this._holidayDate = value;
			}
		}
		
		private string _backgroundClass;
		public virtual string BackgroundClass
		{
			get
			{
				return this._backgroundClass;
			}
			set
			{
				this._backgroundClass = value;
			}
		}
		
	}
}
#pragma warning restore 1591
