#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using LawAppModel;

namespace LawAppModel	
{
	public partial class PaymentLog
	{
		private int _paymentLogID;
		public virtual int PaymentLogID
		{
			get
			{
				return this._paymentLogID;
			}
			set
			{
				this._paymentLogID = value;
			}
		}
		
		private int _subscriptionID;
		public virtual int SubscriptionID
		{
			get
			{
				return this._subscriptionID;
			}
			set
			{
				this._subscriptionID = value;
			}
		}
		
		private string _txn_id;
		public virtual string Txn_id
		{
			get
			{
				return this._txn_id;
			}
			set
			{
				this._txn_id = value;
			}
		}
		
		private string _txn_type;
		public virtual string Txn_type
		{
			get
			{
				return this._txn_type;
			}
			set
			{
				this._txn_type = value;
			}
		}
		
		private string _receiver_email;
		public virtual string Receiver_email
		{
			get
			{
				return this._receiver_email;
			}
			set
			{
				this._receiver_email = value;
			}
		}
		
		private string _payment_status;
		public virtual string Payment_status
		{
			get
			{
				return this._payment_status;
			}
			set
			{
				this._payment_status = value;
			}
		}
		
		private string _payer_email;
		public virtual string Payer_email
		{
			get
			{
				return this._payer_email;
			}
			set
			{
				this._payer_email = value;
			}
		}
		
		private DateTime _createDate;
		public virtual DateTime CreateDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				this._createDate = value;
			}
		}
		
		private Subscription _subscription;
		public virtual Subscription Subscription
		{
			get
			{
				return this._subscription;
			}
			set
			{
				this._subscription = value;
			}
		}
		
	}
}
#pragma warning restore 1591
