#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace LawAppModel	
{
	public partial class Permission
	{
		private int _permissionId;
		public virtual int PermissionId
		{
			get
			{
				return this._permissionId;
			}
			set
			{
				this._permissionId = value;
			}
		}
		
		private string _permissionName;
		public virtual string PermissionName
		{
			get
			{
				return this._permissionName;
			}
			set
			{
				this._permissionName = value;
			}
		}
		
		private bool _requiresLogin;
		public virtual bool RequiresLogin
		{
			get
			{
				return this._requiresLogin;
			}
			set
			{
				this._requiresLogin = value;
			}
		}
		
	}
}
#pragma warning restore 1591
