#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using LawAppModel;

namespace LawAppModel	
{
	public partial class SignedWebUser
	{
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _userPassword;
		public virtual string UserPassword
		{
			get
			{
				return this._userPassword;
			}
			set
			{
				this._userPassword = value;
			}
		}
		
		private int _webUserId;
		public virtual int WebUserId
		{
			get
			{
				return this._webUserId;
			}
			set
			{
				this._webUserId = value;
			}
		}
		
		private DateTime _creationDate;
		public virtual DateTime CreationDate
		{
			get
			{
				return this._creationDate;
			}
			set
			{
				this._creationDate = value;
			}
		}
		
		private DateTime? _modificationDate;
		public virtual DateTime? ModificationDate
		{
			get
			{
				return this._modificationDate;
			}
			set
			{
				this._modificationDate = value;
			}
		}
		
		private bool _imported;
		public virtual bool Imported
		{
			get
			{
				return this._imported;
			}
			set
			{
				this._imported = value;
			}
		}
		
		private Guid? _accountVerifyToken;
		public virtual Guid? AccountVerifyToken
		{
			get
			{
				return this._accountVerifyToken;
			}
			set
			{
				this._accountVerifyToken = value;
			}
		}
		
		private DateTime? _accountVerifyDate;
		public virtual DateTime? AccountVerifyDate
		{
			get
			{
				return this._accountVerifyDate;
			}
			set
			{
				this._accountVerifyDate = value;
			}
		}
		
		private DateTime? _lastLogin;
		public virtual DateTime? LastLogin
		{
			get
			{
				return this._lastLogin;
			}
			set
			{
				this._lastLogin = value;
			}
		}
		
		private Person _person;
		public virtual Person Person
		{
			get
			{
				return this._person;
			}
			set
			{
				this._person = value;
			}
		}
		
		private IList<Permission> _permissions = new List<Permission>();
		public virtual IList<Permission> Permissions
		{
			get
			{
				return this._permissions;
			}
		}
		
		private IList<UserRole> _userRoles = new List<UserRole>();
		public virtual IList<UserRole> UserRoles
		{
			get
			{
				return this._userRoles;
			}
		}
		
		private IList<TSC_Calendar> _tSC_Calendars = new List<TSC_Calendar>();
		public virtual IList<TSC_Calendar> TSC_Calendars
		{
			get
			{
				return this._tSC_Calendars;
			}
		}
		
		private IList<Subscription> _subscriptions = new List<Subscription>();
		public virtual IList<Subscription> Subscriptions
		{
			get
			{
				return this._subscriptions;
			}
		}
		
	}
}
#pragma warning restore 1591
