#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using LawAppModel;

namespace LawAppModel	
{
	public partial class SignedWebUser
	{
		private int _webUserId;
		public virtual int WebUserId
		{
			get
			{
				return this._webUserId;
			}
			set
			{
				this._webUserId = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _userPassword;
		public virtual string UserPassword
		{
			get
			{
				return this._userPassword;
			}
			set
			{
				this._userPassword = value;
			}
		}
		
		private DateTime _creationDate;
		public virtual DateTime CreationDate
		{
			get
			{
				return this._creationDate;
			}
			set
			{
				this._creationDate = value;
			}
		}
		
		private DateTime? _modificationDate;
		public virtual DateTime? ModificationDate
		{
			get
			{
				return this._modificationDate;
			}
			set
			{
				this._modificationDate = value;
			}
		}
		
		private IList<UserRole> _userRoles = new List<UserRole>();
		public virtual IList<UserRole> UserRoles
		{
			get
			{
				return this._userRoles;
			}
		}
		
	}
}
#pragma warning restore 1591
