#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using LawAppModel;

namespace LawAppModel	
{
	public partial class Subscription
	{
		private int _subscriptionID;
		public virtual int SubscriptionID
		{
			get
			{
				return this._subscriptionID;
			}
			set
			{
				this._subscriptionID = value;
			}
		}
		
		private DateTime? _effectiveFrom;
		public virtual DateTime? EffectiveFrom
		{
			get
			{
				return this._effectiveFrom;
			}
			set
			{
				this._effectiveFrom = value;
			}
		}
		
		private DateTime? _effectiveTo;
		public virtual DateTime? EffectiveTo
		{
			get
			{
				return this._effectiveTo;
			}
			set
			{
				this._effectiveTo = value;
			}
		}
		
		private int _subscriptionPlanID;
		public virtual int SubscriptionPlanID
		{
			get
			{
				return this._subscriptionPlanID;
			}
			set
			{
				this._subscriptionPlanID = value;
			}
		}
		
		private bool _active;
		public virtual bool Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private DateTime _createDate;
		public virtual DateTime CreateDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				this._createDate = value;
			}
		}
		
		private DateTime? _modifyDate;
		public virtual DateTime? ModifyDate
		{
			get
			{
				return this._modifyDate;
			}
			set
			{
				this._modifyDate = value;
			}
		}
		
		private DateTime? _inActiveDate;
		public virtual DateTime? InActiveDate
		{
			get
			{
				return this._inActiveDate;
			}
			set
			{
				this._inActiveDate = value;
			}
		}
		
		private Guid? _token;
		public virtual Guid? Token
		{
			get
			{
				return this._token;
			}
			set
			{
				this._token = value;
			}
		}
		
		private DateTime _nextBillDate;
		public virtual DateTime NextBillDate
		{
			get
			{
				return this._nextBillDate;
			}
			set
			{
				this._nextBillDate = value;
			}
		}
		
		private string _payKey;
		public virtual string PayKey
		{
			get
			{
				return this._payKey;
			}
			set
			{
				this._payKey = value;
			}
		}
		
		private SubscriptionPlan _subscriptionPlan;
		public virtual SubscriptionPlan SubscriptionPlan
		{
			get
			{
				return this._subscriptionPlan;
			}
			set
			{
				this._subscriptionPlan = value;
			}
		}
		
		private SignedWebUser _signedWebUser;
		public virtual SignedWebUser SignedWebUser
		{
			get
			{
				return this._signedWebUser;
			}
			set
			{
				this._signedWebUser = value;
			}
		}
		
	}
}
#pragma warning restore 1591
