#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using LawAppModel;

namespace LawAppModel	
{
	public partial class SubscriptionPlan
	{
		private int _subscriptionPlanID;
		public virtual int SubscriptionPlanID
		{
			get
			{
				return this._subscriptionPlanID;
			}
			set
			{
				this._subscriptionPlanID = value;
			}
		}
		
		private string _planName;
		public virtual string PlanName
		{
			get
			{
				return this._planName;
			}
			set
			{
				this._planName = value;
			}
		}
		
		private decimal _planCost;
		public virtual decimal PlanCost
		{
			get
			{
				return this._planCost;
			}
			set
			{
				this._planCost = value;
			}
		}
		
		private bool _isActive;
		public virtual bool IsActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
			}
		}
		
		private int _subscriptionDurationID;
		public virtual int SubscriptionDurationID
		{
			get
			{
				return this._subscriptionDurationID;
			}
			set
			{
				this._subscriptionDurationID = value;
			}
		}
		
		private int _durationLength;
		public virtual int DurationLength
		{
			get
			{
				return this._durationLength;
			}
			set
			{
				this._durationLength = value;
			}
		}
		
		private SubscriptionDuration _subscriptionDuration;
		public virtual SubscriptionDuration SubscriptionDuration
		{
			get
			{
				return this._subscriptionDuration;
			}
			set
			{
				this._subscriptionDuration = value;
			}
		}
		
		private IList<Subscription> _subscriptions = new List<Subscription>();
		public virtual IList<Subscription> Subscriptions
		{
			get
			{
				return this._subscriptions;
			}
		}
		
	}
}
#pragma warning restore 1591
