#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using LawAppModel;

namespace LawAppModel	
{
	public partial class SubscriptionDuration
	{
		private int _subscriptionDurationID;
		public virtual int SubscriptionDurationID
		{
			get
			{
				return this._subscriptionDurationID;
			}
			set
			{
				this._subscriptionDurationID = value;
			}
		}
		
		private string _subscriptionDurationType;
		public virtual string SubscriptionDurationType
		{
			get
			{
				return this._subscriptionDurationType;
			}
			set
			{
				this._subscriptionDurationType = value;
			}
		}
		
		private IList<SubscriptionPlan> _subscriptionPlans = new List<SubscriptionPlan>();
		public virtual IList<SubscriptionPlan> SubscriptionPlans
		{
			get
			{
				return this._subscriptionPlans;
			}
		}
		
	}
}
#pragma warning restore 1591
