#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using LawAppModel;

namespace LawAppModel	
{
	public partial class TSC_Calendar
	{
		private long _calendarId;
		public virtual long CalendarId
		{
			get
			{
				return this._calendarId;
			}
			set
			{
				this._calendarId = value;
			}
		}
		
		private short _year;
		public virtual short Year
		{
			get
			{
				return this._year;
			}
			set
			{
				this._year = value;
			}
		}
		
		private string _exhibit;
		public virtual string Exhibit
		{
			get
			{
				return this._exhibit;
			}
			set
			{
				this._exhibit = value;
			}
		}
		
		private string _caseName;
		public virtual string CaseName
		{
			get
			{
				return this._caseName;
			}
			set
			{
				this._caseName = value;
			}
		}
		
		private string _caseNumber;
		public virtual string CaseNumber
		{
			get
			{
				return this._caseNumber;
			}
			set
			{
				this._caseNumber = value;
			}
		}
		
		private bool _weekendsActive;
		public virtual bool WeekendsActive
		{
			get
			{
				return this._weekendsActive;
			}
			set
			{
				this._weekendsActive = value;
			}
		}
		
		private DateTime? _weekendsStart;
		public virtual DateTime? WeekendsStart
		{
			get
			{
				return this._weekendsStart;
			}
			set
			{
				this._weekendsStart = value;
			}
		}
		
		private bool _displayHolidays;
		public virtual bool DisplayHolidays
		{
			get
			{
				return this._displayHolidays;
			}
			set
			{
				this._displayHolidays = value;
			}
		}
		
		private DateTime _lastSaved;
		public virtual DateTime LastSaved
		{
			get
			{
				return this._lastSaved;
			}
			set
			{
				this._lastSaved = value;
			}
		}
		
		private DateTime _createDate;
		public virtual DateTime CreateDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				this._createDate = value;
			}
		}
		
		private int _webUserId;
		public virtual int WebUserId
		{
			get
			{
				return this._webUserId;
			}
			set
			{
				this._webUserId = value;
			}
		}
		
		private SignedWebUser _signedWebUser;
		public virtual SignedWebUser SignedWebUser
		{
			get
			{
				return this._signedWebUser;
			}
			set
			{
				this._signedWebUser = value;
			}
		}
		
		private IList<TSC_IndividualOvernight> _tSC_IndividualOvernights = new List<TSC_IndividualOvernight>();
		public virtual IList<TSC_IndividualOvernight> TSC_IndividualOvernights
		{
			get
			{
				return this._tSC_IndividualOvernights;
			}
		}
		
		private IList<TSC_Break> _tSC_Breaks = new List<TSC_Break>();
		public virtual IList<TSC_Break> TSC_Breaks
		{
			get
			{
				return this._tSC_Breaks;
			}
		}
		
		private IList<TSC_UniqueDays> _tSC_UniqueDays = new List<TSC_UniqueDays>();
		public virtual IList<TSC_UniqueDays> TSC_UniqueDays
		{
			get
			{
				return this._tSC_UniqueDays;
			}
		}
		
	}
}
#pragma warning restore 1591
