#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using LawAppModel;

namespace LawAppModel	
{
	public partial class TSC_IndividualOvernight
	{
		private long _individualOvernightId;
		public virtual long IndividualOvernightId
		{
			get
			{
				return this._individualOvernightId;
			}
			set
			{
				this._individualOvernightId = value;
			}
		}
		
		private DayOfWeek _dayOfWeek;
		public virtual DayOfWeek DayOfWeek
		{
			get
			{
				return this._dayOfWeek;
			}
			set
			{
				this._dayOfWeek = value;
			}
		}
		
		private bool _everyActive;
		public virtual bool EveryActive
		{
			get
			{
				return this._everyActive;
			}
			set
			{
				this._everyActive = value;
			}
		}
		
		private bool _everyOtherActive;
		public virtual bool EveryOtherActive
		{
			get
			{
				return this._everyOtherActive;
			}
			set
			{
				this._everyOtherActive = value;
			}
		}
		
		private DateTime? _startDate;
		public virtual DateTime? StartDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				this._startDate = value;
			}
		}
		
		private TSC_Calendar _tSC_Calendar;
		public virtual TSC_Calendar TSC_Calendar
		{
			get
			{
				return this._tSC_Calendar;
			}
			set
			{
				this._tSC_Calendar = value;
			}
		}
		
	}
}
#pragma warning restore 1591
