#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using LawAppModel;

namespace LawAppModel	
{
	public partial class TSC_Break
	{
		private long _breakId;
		public virtual long BreakId
		{
			get
			{
				return this._breakId;
			}
			set
			{
				this._breakId = value;
			}
		}
		
		private HolidayBreak _break;
		public virtual HolidayBreak Break
		{
			get
			{
				return this._break;
			}
			set
			{
				this._break = value;
			}
		}
		
		private DateTime? _firstNight;
		public virtual DateTime? FirstNight
		{
			get
			{
				return this._firstNight;
			}
			set
			{
				this._firstNight = value;
			}
		}
		
		private DateTime? _lastNight;
		public virtual DateTime? LastNight
		{
			get
			{
				return this._lastNight;
			}
			set
			{
				this._lastNight = value;
			}
		}
		
		private bool _showBreak;
		public virtual bool ShowBreak
		{
			get
			{
				return this._showBreak;
			}
			set
			{
				this._showBreak = value;
			}
		}
		
		private bool _clearExisting;
		public virtual bool ClearExisting
		{
			get
			{
				return this._clearExisting;
			}
			set
			{
				this._clearExisting = value;
			}
		}
		
		private bool _parentBFirst;
		public virtual bool ParentBFirst
		{
			get
			{
				return this._parentBFirst;
			}
			set
			{
				this._parentBFirst = value;
			}
		}
		
		private bool _parentBSecond;
		public virtual bool ParentBSecond
		{
			get
			{
				return this._parentBSecond;
			}
			set
			{
				this._parentBSecond = value;
			}
		}
		
		private bool _parentBFull;
		public virtual bool ParentBFull
		{
			get
			{
				return this._parentBFull;
			}
			set
			{
				this._parentBFull = value;
			}
		}
		
		private long _calendarId;
		public virtual long CalendarId
		{
			get
			{
				return this._calendarId;
			}
			set
			{
				this._calendarId = value;
			}
		}
		
		private TSC_Calendar _tSC_Calendar;
		public virtual TSC_Calendar TSC_Calendar
		{
			get
			{
				return this._tSC_Calendar;
			}
			set
			{
				this._tSC_Calendar = value;
			}
		}
		
	}
}
#pragma warning restore 1591
