#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace LawAppModel	
{
	public partial class WebUser
	{
		private int _webUserId;
		public virtual int WebUserId
		{
			get
			{
				return this._webUserId;
			}
			set
			{
				this._webUserId = value;
			}
		}
		
		private DateTime _creationDate;
		public virtual DateTime CreationDate
		{
			get
			{
				return this._creationDate;
			}
			set
			{
				this._creationDate = value;
			}
		}
		
		private DateTime? _modificationDate;
		public virtual DateTime? ModificationDate
		{
			get
			{
				return this._modificationDate;
			}
			set
			{
				this._modificationDate = value;
			}
		}
		
		private string _voa_class;
		public virtual string Voa_class
		{
			get
			{
				return this._voa_class;
			}
			set
			{
				this._voa_class = value;
			}
		}
		
	}
}
#pragma warning restore 1591
