// Code is generated by Telerik Data Access Service Wizard
// using WebApiRepositories.tt template

using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Telerik.OpenAccess;
using LawAppModel;

namespace LawAppWeb
{
	public partial class ApplicationRepository : OpenAccessBaseRepository<LawAppModel.Application, LawAppModel.LawApp>
    {
	
    }

	public partial class HolidayRepository : OpenAccessBaseRepository<LawAppModel.Holiday, LawAppModel.LawApp>
    {
	
    }

	public partial class PermissionRepository : OpenAccessBaseRepository<LawAppModel.Permission, LawAppModel.LawApp>
    {
	
    }

	public partial class PersonRepository : OpenAccessBaseRepository<LawAppModel.Person, LawAppModel.LawApp>
    {
	
    }

	public partial class SignedWebUserRepository : OpenAccessBaseRepository<LawAppModel.SignedWebUser, LawAppModel.LawApp>
    {
	
    }

	public partial class TSC_BreakRepository : OpenAccessBaseRepository<LawAppModel.TSC_Break, LawAppModel.LawApp>
    {
	
    }

	public partial class TSC_CalendarRepository : OpenAccessBaseRepository<LawAppModel.TSC_Calendar, LawAppModel.LawApp>
    {
	
    }

	public partial class TSC_IndividualOvernightRepository : OpenAccessBaseRepository<LawAppModel.TSC_IndividualOvernight, LawAppModel.LawApp>
    {
	
    }

	public partial class TSC_UniqueDaysRepository : OpenAccessBaseRepository<LawAppModel.TSC_UniqueDays, LawAppModel.LawApp>
    {
	
    }

	public partial class UserRoleRepository : OpenAccessBaseRepository<LawAppModel.UserRole, LawAppModel.LawApp>
    {
	
    }

}
