// Code is generated by Telerik Data Access Service Wizard
// using WebApiRepositories.tt template

using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Telerik.OpenAccess;
using LawAppModel;

namespace LawApp
{
	public partial class ApplicationRepository : OpenAccessBaseRepository<LawAppModel.Application, LawAppModel.LawApp>
    {
	
    }

	public partial class SignedWebUserRepository : OpenAccessBaseRepository<LawAppModel.SignedWebUser, LawAppModel.LawApp>
    {
	
    }

	public partial class UserRoleRepository : OpenAccessBaseRepository<LawAppModel.UserRole, LawAppModel.LawApp>
    {
	
    }

	public partial class WebUserRepository : OpenAccessBaseRepository<LawAppModel.WebUser, LawAppModel.LawApp>
    {
	
    }

}
